1) To create table GYM

CREATE TABLE GYM (
    GYM_ID INTEGER PRIMARY KEY,
    GYM_NAME VARCHAR2(50)
);

2) To create table BRANCH

CREATE TABLE BRANCH (
    BRANCH_ID INTEGER PRIMARY KEY,
    BRANCH_NAME VARCHAR2(50),
    GYM_ID INTEGER,
    ADDRESS_CITY VARCHAR2(30),
    ADDRESS_STREET VARCHAR2(30),
    ADDRESS_PINCODE VARCHAR2(10),
    CONSTRAINT FK_BRANCH_GYM FOREIGN KEY (GYM_ID)
        REFERENCES GYM(GYM_ID)
);

3) To create table MEMBER

CREATE TABLE MEMBER (
    MEMBER_ID INTEGER PRIMARY KEY,
    BRANCH_ID INTEGER,
    MEMBER_NAME VARCHAR2(50),
    GENDER VARCHAR2(10),
    AGE INTEGER,
    BODY_TYPE VARCHAR2(20),
    WEIGHT INTEGER,
    JOINING_DATE DATE,
    ADDRESS_CITY VARCHAR2(30),
    ADDRESS_STREET VARCHAR2(30),
    ADDRESS_PINCODE VARCHAR2(10),
    CONSTRAINT CHK_MEMBER_GENDER
        CHECK (GENDER IN ('MALE', 'FEMALE', 'OTHER')),
    CONSTRAINT CHK_MEMBER_AGE
        CHECK (AGE > 0),
    CONSTRAINT CHK_MEMBER_BODYTYPE
        CHECK (BODY_TYPE IN ('MESODERM', 'ENDODERM', 'ECTODERM')),
    CONSTRAINT FK_MEMBER_BRANCH
        FOREIGN KEY (BRANCH_ID)
        REFERENCES BRANCH(BRANCH_ID)
);

4) To create table TRAINER

CREATE TABLE TRAINER (
    TRAINER_ID INTEGER PRIMARY KEY,
    TRAINER_NAME VARCHAR2(50),
    DATE_OF_BIRTH DATE,
    AGE INTEGER,
    JOINING_DATE DATE,
    EXPERIENCE INTEGER,
    SALARY FLOAT,
    ADDRESS_CITY VARCHAR2(30),
    ADDRESS_STREET VARCHAR2(30),
    ADDRESS_PINCODE VARCHAR2(10)
);

9) Modify the WEIGHT from INTEGER to FLOAT

ALTER TABLE MEMBER
MODIFY WEIGHT FLOAT;

10) To create table STAFF

CREATE TABLE STAFF (
    STAFF_ID INTEGER PRIMARY KEY,
    BRANCH_ID INTEGER,
    STAFF_NAME VARCHAR2(50),
    DATE_OF_BIRTH DATE,
    AGE INTEGER,
    JOINING_DATE DATE,
    EXPERIENCE INTEGER,
    SALARY FLOAT,
    ADDRESS_CITY VARCHAR2(30),
    ADDRESS_STREET VARCHAR2(30),
    ADDRESS_PINCODE VARCHAR2(10),
    CONSTRAINT FK_STAFF_BRANCH FOREIGN KEY (BRANCH_ID)
        REFERENCES BRANCH(BRANCH_ID)
);

11) Add constraint: age ≥ 10 for STAFF

ALTER TABLE STAFF
ADD CONSTRAINT CHK_STAFF_AGE
CHECK (AGE >= 10);

12) To create table SUPPLIER

CREATE TABLE SUPPLIER (
    SUPPLIER_ID INTEGER PRIMARY KEY,
    SUPPLIER_NAME VARCHAR2(50),
    BRANCH_ID INTEGER,
    AMOUNT FLOAT,
    GST_NUMBER VARCHAR2(20),
    CONSTRAINT FK_SUPPLIER_BRANCH FOREIGN KEY (BRANCH_ID)
        REFERENCES BRANCH(BRANCH_ID)
);

13) To create table PAYMENT

CREATE TABLE PAYMENT (
    PAYMENT_ID INTEGER PRIMARY KEY,
    PAYMENT_DATE DATE,
    STATUS VARCHAR2(20),
    BRANCH_ID INTEGER,
    AMOUNT FLOAT,
    CONSTRAINT FK_PAYMENT_BRANCH FOREIGN KEY (BRANCH_ID)
        REFERENCES BRANCH(BRANCH_ID)
);

16) Copy table PAYMENT

CREATE TABLE PAY AS SELECT * FROM PAYMENT;

18) Rename PAY to PAYMENT_II

RENAME PAY TO PAYMENT_II;

19) To create table CARD

CREATE TABLE CARD (
    CARD_ID INTEGER PRIMARY KEY,
    MODES VARCHAR2(20),
    PAYMENT_ID INTEGER,
    CONSTRAINT FK_CARD_PAYMENT
        FOREIGN KEY (PAYMENT_ID)
        REFERENCES PAYMENT(PAYMENT_ID)
);

21) To create table CASH

CREATE TABLE CASH (
    PAYMENT_ID INTEGER PRIMARY KEY,
    BALANCE FLOAT,
    RECEIVED_AMOUNT FLOAT,
    CONSTRAINT FK_CASH_PAYMENT FOREIGN KEY (PAYMENT_ID)
        REFERENCES PAYMENT(PAYMENT_ID)
);

23) To create table INVOICE

CREATE TABLE INVOICE (
    INVOICE_ID INTEGER PRIMARY KEY,
    TAX FLOAT,
    INVOICE_DATE DATE,
    TOTAL_AMOUNT FLOAT,
    PAYMENT_ID INTEGER,
    CONSTRAINT FK_INVOICE_PAYMENT FOREIGN KEY (PAYMENT_ID)
        REFERENCES PAYMENT(PAYMENT_ID)
);

25) To create table INVOICE_LINE

CREATE TABLE INVOICE_LINE(
    LINE_ID INTEGER,
    INVOICE_ID INTEGER NOT NULL,
    QUANTITY INTEGER,
    LINE VARCHAR2(50),
    UNIT_PRICE FLOAT,
    CONSTRAINT FK_LINE_INVOICE FOREIGN KEY (INVOICE_ID)
        REFERENCES INVOICE(INVOICE_ID)
);

29) To create table MEMBERSHIP

CREATE TABLE MEMBERSHIP (
    MEMBERSHIP_ID INTEGER NOT NULL,
    MEMBER_ID INTEGER,
    BRANCH_ID INTEGER,
    DURATION INTEGER,
    TYPE VARCHAR2(20),
    AMOUNT FLOAT,
    START_DATE DATE,
    END_DATE DATE,
    CONSTRAINT PK_MEMBERSHIP PRIMARY KEY (MEMBERSHIP_ID, MEMBER_ID),
    CONSTRAINT FK_MEMBERSHIP_MEMBER FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID),
    CONSTRAINT FK_MEMBERSHIP_BRANCH FOREIGN KEY (BRANCH_ID)
        REFERENCES BRANCH(BRANCH_ID)
);

31) To create table TAKES_WORKOUT_PLAN

CREATE TABLE TAKES_WORKOUT_PLAN (
    MEMBER_ID INTEGER,
    PLAN_ID INTEGER,
    START_DATE DATE,
    END_DATE DATE,
    CONSTRAINT PK_TAKES_WORKOUT PRIMARY KEY (MEMBER_ID, PLAN_ID),
    CONSTRAINT FK_TAKES_WORKOUT_MEMBER FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(MEMBER_ID),
    CONSTRAINT FK_TAKES_WORKOUT_PLAN FOREIGN KEY (PLAN_ID)
        REFERENCES WORKOUT_PLAN(PLAN_ID)
);

33) To create table TRAINER_SPECIALISATION

CREATE TABLE TRAINER_SPECIALISATION (
    TRAINER_ID INTEGER,
    SPECIALISATION VARCHAR2(30),
    CONSTRAINT PK_TRAINER_SPEC PRIMARY KEY (TRAINER_ID, SPECIALISATION),
    CONSTRAINT FK_TRAINER_SPEC FOREIGN KEY (TRAINER_ID)
        REFERENCES TRAINER(TRAINER_ID)
);

35) Add constraint for PAYMENT STATUS

ALTER TABLE PAYMENT
ADD CONSTRAINT CHK_PAYMENT_STATUS
CHECK (STATUS IN ('PAID', 'PENDING', 'FAILED'));

36) Add constraint for MEMBERSHIP dates

ALTER TABLE MEMBERSHIP
ADD CONSTRAINT CHK_MEMBERSHIP_DATE
CHECK (END_DATE > START_DATE);

37) Truncate INVOICE_LINE

TRUNCATE TABLE INVOICE_LINE;

38) Drop table PAYMENT_II

DROP TABLE PAYMENT_II;

39) Drop column SETS from WORKOUT_PLAN

ALTER TABLE WORKOUT_PLAN DROP COLUMN SETS;

40) Add column STATUS to TAKES_WORKOUT_PLAN

ALTER TABLE TAKES_WORKOUT_PLAN ADD STATUS VARCHAR2(20);

41) Drop column STATUS from TAKES_WORKOUT_PLAN

ALTER TABLE TAKES_WORKOUT_PLAN DROP COLUMN STATUS;

42) Add primary key to TAKES_WORKOUT_PLAN

ALTER TABLE TAKES_WORKOUT_PLAN ADD CONSTRAINT PK_WORKOUT PRIMARY KEY(PLAN_ID);

43) Drop primary key from TAKES_WORKOUT_PLAN

ALTER TABLE TAKES_WORKOUT_PLAN DROP PRIMARY KEY;

44) Add CHECK constraint to TRAINER

ALTER TABLE TRAINER ADD CONSTRAINT CHK_AGE CHECK(AGE>=18);

45) Drop CHECK constraint from TRAINER

ALTER TABLE TRAINER DROP CONSTRAINT CHK_AGE;

46) Rename column in MEMBER table

ALTER TABLE MEMBER RENAME COLUMN JOINING_DATE TO DATE_OF_JOIN;

47) Add foreign key to CARD

ALTER TABLE CARD ADD CONSTRAINT FK_CARD_PAYMENT 
FOREIGN KEY(PAYMENT_ID) REFERENCES PAYMENT(PAYMENT_ID);

48) Drop foreign key from CARD

ALTER TABLE CARD DROP CONSTRAINT FK_CARD_PAYMENT;
